spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  main:
    #当遇到同样名字的时候，是否允许覆盖注册——解决redisTemplate重名问题
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3306/dtu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

# Redis数据库索引（默认为0）
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000

  #jpa 测试
  jpa:
    hibernate:
      ddl-auto: create-drop # 新增数据库链接必须的参数
    # 控制台显示SQL
#    show-sql: true
    properties:
      hibernate:
        #每次初始化一个实体的关联就会创建一个临时的session来加载，请求的session是被立即关闭的，也就是在读取了基本属性后，session 已经close了，再进行 lazy loaiding 就会有异常
        enable_lazy_load_no_trans: true
      hibernate.format_sql: true
    open-in-view: true
#配置netty端口号
nettyPort: 9090