spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  #jpa 测试
  jpa:
    hibernate:
      ddl-auto: create-drop # 新增数据库链接必须的参数
    # 控制台显示SQL
    show-sql: true
    properties:
      hibernate.format_sql: true
nettyport: 9090